# <font color='green'> 2.1 Crear arrays multidimencionales </font>

## <font color='blue'> Numpy </font>

### `NumPy` (abreviacion de Numerical Python) es un paquete para computacion cientifica avanzada y analisis de datos. Proporciona funcionalidades especificas para manipular datos de tipo array.

### Un `array` es una estructura de datos 

### Debemos empezar por importar el modulo *numpy*.

In [12]:
import numpy as np

In [13]:
arreglo = np.array([0,1,2,3,4,5])

In [14]:
arreglo, type(arreglo)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [15]:
notas = [6,7,8,9,10]
ar_notas = np.array(notas, dtype=float)

In [16]:
ar_notas, type(ar_notas[0])

(array([ 6.,  7.,  8.,  9., 10.]), numpy.float64)

In [17]:
ar_notas_todas = np.array(([0, 1, 2, 3, 4, 5], notas), dtype=object)
ar_notas_todas

array([list([0, 1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10])], dtype=object)

## <font color='Blue'> *ndim* </font>

### El atributo `ndim` nos indica cuantas dimenciones tiene el `array`

In [18]:
print(ar_notas_todas.ndim)
print(ar_notas.ndim)

1
1


## <font color='Blue'> *shape* </font>

### El atributo `ndim` nos indica el tamaño de cada dimension del `array`

In [19]:
print(ar_notas_todas.shape)
print(ar_notas.shape)

(2,)
(5,)


## <font color='Blue'> *Arrays especiales* </font>

* `zeros`: Produce un ndarray con todos sus elementos igual a cero.
* `ones`: Produce un ndarray con todos sus elementos igual a uno.
* `identity`: Produce la matriz cuadrada identidad.
* `arange`: Produce un nuevo `ndarray` cuyos elementos elementos estan en el rango especifico.

In [20]:
arr = np.zeros((2,3), dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr_2 = np.ones((3,4), dtype=float)
print(arr_2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
arr_3 = np.identity((4), dtype=float)
print(arr_3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
arr_4 = np.arange(1,9)
print(arr_4)

[1 2 3 4 5 6 7 8]
